#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <thread>
#include <mutex>
#include <vector>
#include <cstring>
#include <ctime>
#include <netinet/in.h>
#include <unistd.h>
#include <algorithm> // For std::min
#include <openssl/sha.h> 
#include <iomanip>
#include <openssl/evp.h> 
#include <openssl/rand.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <sodium.h>
#include "tls_common.h"   // TLS transport helpers (tls_send/tls_recv/tls_read_line/...)

// ---- TEMPORARY: Signed Session Token debug verification logging ----
// Set to 0 (or delete this block + the TOKEN_DEBUG-guarded lines below)
// once the Phase 1 token rollout is verified. Purely additive cout/cerr
// statements - no protocol, security, or control-flow changes.
#define TOKEN_DEBUG 1

#define PORT 4444
#define VERIFY_PORT 4446   // internal, server-to-server session verification port
#define BUFFER_SIZE 4096
#define SESSION_TOKEN_BYTES 32
#define SESSION_TOKEN_TTL_SECONDS 120  // signed-token validity window (2 minutes)

// Paths to this server's TLS identity (self-signed, generated by certs/gen_certs.sh).
// Both the public client-facing port (4444) and the internal verify port
// (4446) present this same certificate.
#define TLS_CERT_PATH "certs/gmailserver_cert.pem"
#define TLS_KEY_PATH  "certs/gmailserver_key.pem"

// ---- Signed Session Tokens (Phase 1) ----
// Separate from the TLS identity above: this is GmailServer's own RSA
// keypair, used ONLY to sign session tokens. Generated once at startup if
// missing (same pattern KeyServer already uses for its own
// keyserver_private.pem/keyserver_public.pem). KeyServer and RecoveryServer
// load gmailserver_public.pem (read-only on their side) to verify tokens;
// neither server ever generates this keypair - only GmailServer does.
#define GMAIL_SIGNING_KEY_SIZE 2048
#define GMAIL_SIGNING_PRIVATE_KEY_PATH "gmailserver_private.pem"
#define GMAIL_SIGNING_PUBLIC_KEY_PATH  "gmailserver_public.pem"

using namespace std;

mutex file_mutex;
unordered_map<string, string> userDatabase;

// --- Session tracking for cross-server identity verification ---
// Maps username -> {session token, currently connected?}
struct SessionInfo {
    string token;
    bool connected;
};
mutex session_mutex;
unordered_map<string, SessionInfo> activeSessions;

// ---- One-Time Operation Tokens (Phase 2) ----
// Separate, additive layer on top of Signed Session Tokens above. An
// Operation Token (OT) is short-lived, single-use, and scoped to exactly
// one (username, operation, target_service) triple. It does NOT replace
// the session token: every share-related call still carries its existing
// session_token (verified exactly as before), AND now also carries one
// OT consumed for that specific call.
//
// Maps op_nonce -> OperationToken. Keyed by nonce (not the full token
// string) so lookup/consume in handleVerifyConnection's VERIFY_OP branch
// is a simple, fast map operation independent of token string formatting.
struct OperationToken {
    string username;
    string operation;       // e.g. "FETCH_SHARE1", "STORE_SHARE2", ...
    string target_service;  // "KEYSERVER" or "RECOVERYSERVER"
    time_t expires_at;
    bool used;
};
mutex op_token_mutex;
unordered_map<string, OperationToken> activeOpTokens;
#define OP_TOKEN_TTL_SECONDS 30   // short-lived: bridges "request OT" -> "use OT immediately after"

// ---- Signed Session Tokens (Phase 1): base64 helper ----
// Standard alphabet, no embedded newlines - safe to carry inside both the
// '\n'-delimited AUTH_SUCCESS response and the '|'-delimited wire messages
// (STORE_SHARE1|username|session_token|..., etc.) used elsewhere in this
// project, since standard base64 output never contains '|' or '\n'.
string base64Encode(const unsigned char* input, size_t length) {
    BIO* b64 = BIO_new(BIO_f_base64());
    BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
    BIO* mem = BIO_new(BIO_s_mem());
    BIO_push(b64, mem);
    BIO_write(b64, input, (int)length);
    BIO_flush(b64);

    BUF_MEM* bufferPtr;
    BIO_get_mem_ptr(b64, &bufferPtr);
    string encoded(bufferPtr->data, bufferPtr->length);
    BIO_free_all(b64);
    return encoded;
}

string base64Decode(const string& encoded) {
    BIO* b64 = BIO_new(BIO_f_base64());
    BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
    BIO* mem = BIO_new_mem_buf(encoded.data(), (int)encoded.size());
    BIO_push(b64, mem);

    vector<unsigned char> buf(encoded.size());
    int decoded_len = BIO_read(b64, buf.data(), (int)buf.size());
    BIO_free_all(b64);
    if (decoded_len <= 0) return "";
    return string(reinterpret_cast<char*>(buf.data()), decoded_len);
}

// ---- Signed Session Tokens (Phase 1): GmailServer signing keypair ----
// Separate from the TLS identity (certs/gmailserver_*.pem). Generated once
// if missing, mirroring KeyServer's generateServerKeys()/loadServerPrivateKey()
// pattern (keyserver.cpp). Only GmailServer ever writes these two files;
// KeyServer/RecoveryServer only ever read gmailserver_public.pem.
void generateGmailSigningKeys() {
    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, nullptr);
    if (!ctx) {
        cerr << "ERROR: Could not create EVP_PKEY_CTX for signing keypair" << endl;
        return;
    }
    if (EVP_PKEY_keygen_init(ctx) <= 0 ||
        EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, GMAIL_SIGNING_KEY_SIZE) <= 0) {
        cerr << "ERROR: Could not initialize signing keypair generation" << endl;
        EVP_PKEY_CTX_free(ctx);
        return;
    }

    EVP_PKEY* pkey = nullptr;
    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {
        cerr << "ERROR: Could not generate signing keypair" << endl;
        EVP_PKEY_CTX_free(ctx);
        return;
    }

    BIO* bio_private = BIO_new_file(GMAIL_SIGNING_PRIVATE_KEY_PATH, "w+");
    if (bio_private) {
        PEM_write_bio_PrivateKey(bio_private, pkey, nullptr, nullptr, 0, nullptr, nullptr);
        BIO_free(bio_private);
    } else {
        cerr << "ERROR: Could not open " << GMAIL_SIGNING_PRIVATE_KEY_PATH << " for writing" << endl;
    }

    BIO* bio_public = BIO_new_file(GMAIL_SIGNING_PUBLIC_KEY_PATH, "w+");
    if (bio_public) {
        PEM_write_bio_PUBKEY(bio_public, pkey);
        BIO_free(bio_public);
    } else {
        cerr << "ERROR: Could not open " << GMAIL_SIGNING_PUBLIC_KEY_PATH << " for writing" << endl;
    }

    EVP_PKEY_free(pkey);
    EVP_PKEY_CTX_free(ctx);
    cout << "[TOKEN] GmailServer signing keypair generated successfully." << endl;
}

EVP_PKEY* loadGmailSigningPrivateKey() {
    BIO* bio = BIO_new_file(GMAIL_SIGNING_PRIVATE_KEY_PATH, "r");
    if (!bio) {
        cerr << "ERROR: Could not open " << GMAIL_SIGNING_PRIVATE_KEY_PATH << endl;
        return nullptr;
    }
    EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, nullptr, nullptr, nullptr);
    BIO_free(bio);
    if (!pkey) {
        cerr << "ERROR: Could not parse " << GMAIL_SIGNING_PRIVATE_KEY_PATH << endl;
    }
    return pkey;
}

// Signs `data` with GmailServer's signing private key (RSA-SHA256, same
// EVP_DigestSign* primitive already used for email/HMAC signing elsewhere
// in this codebase). Returns base64-encoded signature, or "" on failure.
string signWithGmailKey(const string& data) {
    EVP_PKEY* pkey = loadGmailSigningPrivateKey();
    if (!pkey) return "";

    EVP_MD_CTX* md_ctx = EVP_MD_CTX_new();
    if (!md_ctx) {
        EVP_PKEY_free(pkey);
        return "";
    }

    string result;
    size_t sig_len = 0;
    if (EVP_DigestSignInit(md_ctx, nullptr, EVP_sha256(), nullptr, pkey) > 0 &&
        EVP_DigestSignUpdate(md_ctx, data.data(), data.size()) > 0 &&
        EVP_DigestSignFinal(md_ctx, nullptr, &sig_len) > 0) {
        vector<unsigned char> sig(sig_len);
        if (EVP_DigestSignFinal(md_ctx, sig.data(), &sig_len) > 0) {
            result = base64Encode(sig.data(), sig_len);
        }
    }
    if (result.empty()) {
        cerr << "ERROR: Failed to sign session token payload" << endl;
    }

    EVP_MD_CTX_free(md_ctx);
    EVP_PKEY_free(pkey);
    return result;
}

// ---- Signed Session Tokens (Phase 1): token construction ----
// Token shape: base64(payload) + "." + base64(signature)
//   payload = "username|issued_at|expires_at|nonce"
//   signature = RSA-SHA256 signature (GmailServer signing key) over `payload`
//
// Using base64-of-the-whole-payload (rather than embedding raw '|' fields
// directly in the outer token string) means the only character the token
// itself can ever contain besides base64's own alphabet is the single '.'
// separator - so it stays safe to carry through the existing
// '\n'-delimited AUTH_SUCCESS response and every existing '|'-delimited
// wire message without any change to those formats or their parsers.
string generateSessionToken(const string& username) {
    unsigned char nonce_raw[SESSION_TOKEN_BYTES];
    if (RAND_bytes(nonce_raw, SESSION_TOKEN_BYTES) != 1) {
        cerr << "ERROR: Failed to generate session token nonce" << endl;
        return "";
    }
    stringstream nonce_ss;
    for (int i = 0; i < SESSION_TOKEN_BYTES; i++) {
        nonce_ss << hex << setw(2) << setfill('0') << (int)nonce_raw[i];
    }
    string nonce = nonce_ss.str();

    time_t now = time(nullptr);
    time_t expires = now + SESSION_TOKEN_TTL_SECONDS;

    string payload = username + "|" + to_string((long long)now) + "|" +
                      to_string((long long)expires) + "|" + nonce;

    string signature = signWithGmailKey(payload);
    if (signature.empty()) {
        cerr << "ERROR: Failed to sign session token" << endl;
        return "";
    }

#if TOKEN_DEBUG
    cout << "[TOKEN] Generated signed session token" << endl;
    cout << "[TOKEN] Username = " << username << endl;
    cout << "[TOKEN] Issued At = " << now << endl;
    cout << "[TOKEN] Expires At = " << expires << endl;
    cout << "[TOKEN] Nonce = " << nonce << endl;
#endif

    return base64Encode(reinterpret_cast<const unsigned char*>(payload.data()), payload.size())
           + "." + signature;
}

// Mark a user as authenticated and return their fresh session token
string startSession(const string& username) {
    string token = generateSessionToken(username);
    if (token.empty()) return "";
    lock_guard<mutex> lock(session_mutex);
    activeSessions[username] = {token, true};
    return token;
}

// Mark a user's session as ended (called on disconnect/logout)
void endSession(const string& username) {
    if (username.empty()) return;
    lock_guard<mutex> lock(session_mutex);
    auto it = activeSessions.find(username);
    if (it != activeSessions.end()) {
        it->second.connected = false;
    }
}

// Internal: check whether (username, token) is a currently-connected, valid session
bool isSessionValid(const string& username, const string& token) {
    lock_guard<mutex> lock(session_mutex);
    auto it = activeSessions.find(username);
#if TOKEN_DEBUG
    cout << "[TOKEN] Username = " << username << endl;
    cout << "[TOKEN] Session found = " << (it != activeSessions.end() ? "yes" : "no") << endl;
#endif
    if (it == activeSessions.end()) {
#if TOKEN_DEBUG
        cout << "[TOKEN] Result = INVALID (no session for this username)" << endl;
#endif
        return false;
    }
    bool valid = it->second.connected && it->second.token == token;

    // Additionally check the token's own signed expires_at field, so a
    // session token already past its TTL is rejected here even while the
    // underlying connection is still open and the token string still
    // matches what was issued. Token payload format is unchanged:
    // base64(payload) + "." + base64(signature), payload =
    // "username|issued_at|expires_at|nonce" - same parsing already used
    // by verifyTokenSignature() in keyserver.cpp/recovery_server.cpp.
    if (valid) {
        size_t dot = token.find('.');
        bool expiry_ok = false;
        if (dot != string::npos && dot != 0 && dot != token.size() - 1) {
            string payload = base64Decode(token.substr(0, dot));
            size_t p1 = payload.find('|');
            size_t p2 = (p1 == string::npos) ? string::npos : payload.find('|', p1 + 1);
            size_t p3 = (p2 == string::npos) ? string::npos : payload.find('|', p2 + 1);
            if (p1 != string::npos && p2 != string::npos && p3 != string::npos) {
                string expires_at_str = payload.substr(p2 + 1, p3 - p2 - 1);
                try {
                    long long expires_at = stoll(expires_at_str);
                    expiry_ok = (time(nullptr) <= (time_t)expires_at);
                } catch (...) {
                    expiry_ok = false;
                }
            }
        }
        valid = valid && expiry_ok;
#if TOKEN_DEBUG
        cout << "[TOKEN] Token expiry check = " << (expiry_ok ? "PASSED" : "FAILED") << endl;
#endif
    }

#if TOKEN_DEBUG
    cout << "[TOKEN] Session connected = " << (it->second.connected ? "yes" : "no") << endl;
    cout << "[TOKEN] Token matches stored session token = " << (it->second.token == token ? "yes" : "no") << endl;
    cout << "[TOKEN] Result = " << (valid ? "VALID" : "INVALID") << endl;
#endif
    return valid;
}

// ---- One-Time Operation Tokens (Phase 2): token construction ----
// Token shape mirrors the signed session token exactly, for the same
// "safe to carry through existing '\n'/'|' delimited wire formats" reason:
//   base64(payload) + "." + base64(signature)
//   payload = "username|operation|target_service|issued_at|expires_at|nonce"
//   signature = RSA-SHA256 over payload, signed with GmailServer's signing
//               key (same key/function as session tokens - signWithGmailKey)
//
// Requires the caller to already hold a VALID session token (checked by
// the REQUEST_OP_TOKEN handler before this is called) - an Operation
// Token is never a substitute for being logged in, only an additional,
// narrower-scoped, single-use credential layered on top.
string generateOperationToken(const string& username, const string& operation,
                               const string& target_service) {
    unsigned char nonce_raw[SESSION_TOKEN_BYTES];
    if (RAND_bytes(nonce_raw, SESSION_TOKEN_BYTES) != 1) {
        cerr << "ERROR: Failed to generate operation token nonce" << endl;
        return "";
    }
    stringstream nonce_ss;
    for (int i = 0; i < SESSION_TOKEN_BYTES; i++) {
        nonce_ss << hex << setw(2) << setfill('0') << (int)nonce_raw[i];
    }
    string nonce = nonce_ss.str();

    time_t now = time(nullptr);
    time_t expires = now + OP_TOKEN_TTL_SECONDS;

    string payload = username + "|" + operation + "|" + target_service + "|" +
                      to_string((long long)now) + "|" + to_string((long long)expires) +
                      "|" + nonce;

    string signature = signWithGmailKey(payload);
    if (signature.empty()) {
        cerr << "ERROR: Failed to sign operation token" << endl;
        return "";
    }

    {
        lock_guard<mutex> lock(op_token_mutex);
        activeOpTokens[nonce] = OperationToken{username, operation, target_service, expires, false};
    }

#if TOKEN_DEBUG
    cout << "[OPTOKEN] Issued operation token: user=" << username
         << " op=" << operation << " target=" << target_service
         << " expires_at=" << expires << endl;
#endif

    return base64Encode(reinterpret_cast<const unsigned char*>(payload.data()), payload.size())
           + "." + signature;
}

// ---- One-Time Operation Tokens (Phase 2): atomic verify-and-consume ----
// Result codes distinguish *why* a token was rejected (reused vs expired
// vs wrong operation/target vs unknown/malformed) so KeyServer/RecoveryServer
// can log meaningfully and so the new replay/expiry/scope tests can assert
// on the specific failure reason rather than just pass/fail.
enum class OpTokenResult { VALID, USED, EXPIRED, WRONG_OPERATION, WRONG_TARGET, NOT_FOUND, MALFORMED };

const char* opTokenResultStr(OpTokenResult r) {
    switch (r) {
        case OpTokenResult::VALID:           return "VALID";
        case OpTokenResult::USED:            return "USED";
        case OpTokenResult::EXPIRED:         return "EXPIRED";
        case OpTokenResult::WRONG_OPERATION: return "WRONG_OPERATION";
        case OpTokenResult::WRONG_TARGET:    return "WRONG_TARGET";
        case OpTokenResult::NOT_FOUND:       return "NOT_FOUND";
        default:                             return "MALFORMED";
    }
}

// Verifies the token's RSA signature (defense in depth, same as session
// tokens - the nonce-keyed map lookup below is the primary check, but an
// attacker who can't forge GmailServer's signature can't even produce a
// nonce that maps to a token they don't already legitimately hold), then
// atomically checks-and-sets the `used` flag under op_token_mutex so two
// concurrent VERIFY_OP calls for the same token cannot both succeed
// (closes the TOCTOU race called out in the architecture review).
OpTokenResult verifyAndConsumeOperationToken(const string& expected_username,
                                              const string& expected_operation,
                                              const string& expected_target,
                                              const string& token) {
    size_t dot = token.find('.');
    if (dot == string::npos || dot == 0 || dot == token.size() - 1) {
        return OpTokenResult::MALFORMED;
    }

    string payload = base64Decode(token.substr(0, dot));
    string signature = base64Decode(token.substr(dot + 1));
    if (payload.empty() || signature.empty()) {
        return OpTokenResult::MALFORMED;
    }

    // Parse payload: username|operation|target_service|issued_at|expires_at|nonce
    size_t p1 = payload.find('|');
    size_t p2 = (p1 == string::npos) ? string::npos : payload.find('|', p1 + 1);
    size_t p3 = (p2 == string::npos) ? string::npos : payload.find('|', p2 + 1);
    size_t p4 = (p3 == string::npos) ? string::npos : payload.find('|', p3 + 1);
    size_t p5 = (p4 == string::npos) ? string::npos : payload.find('|', p4 + 1);
    if (p1 == string::npos || p2 == string::npos || p3 == string::npos ||
        p4 == string::npos || p5 == string::npos) {
        return OpTokenResult::MALFORMED;
    }

    string nonce = payload.substr(p5 + 1);

    // Verify signature using GmailServer's own signing key. GmailServer
    // signs with its private key (signWithGmailKey) the same way it does
    // for session tokens; verify here with the matching public key via
    // the same EVP_DigestVerify* primitive KeyServer/RecoveryServer use.
    EVP_PKEY* pub = nullptr;
    {
        BIO* bio = BIO_new_file(GMAIL_SIGNING_PUBLIC_KEY_PATH, "r");
        if (bio) {
            pub = PEM_read_bio_PUBKEY(bio, nullptr, nullptr, nullptr);
            BIO_free(bio);
        }
    }
    if (!pub) {
        cerr << "ERROR: Could not load " << GMAIL_SIGNING_PUBLIC_KEY_PATH << " for OT verification" << endl;
        return OpTokenResult::MALFORMED;
    }
    EVP_MD_CTX* md_ctx = EVP_MD_CTX_new();
    bool sig_ok = false;
    if (md_ctx &&
        EVP_DigestVerifyInit(md_ctx, nullptr, EVP_sha256(), nullptr, pub) > 0 &&
        EVP_DigestVerifyUpdate(md_ctx, payload.data(), payload.size()) > 0) {
        sig_ok = EVP_DigestVerifyFinal(
            md_ctx, reinterpret_cast<const unsigned char*>(signature.data()), signature.size()) == 1;
    }
    if (md_ctx) EVP_MD_CTX_free(md_ctx);
    EVP_PKEY_free(pub);

    if (!sig_ok) {
        return OpTokenResult::MALFORMED;
    }

    // Atomic check-and-set: look up by nonce, validate, and flip `used`
    // all under one lock acquisition. This single critical section is
    // what makes reuse fail deterministically even under concurrent
    // VERIFY_OP calls for the same token.
    lock_guard<mutex> lock(op_token_mutex);
    auto it = activeOpTokens.find(nonce);
    if (it == activeOpTokens.end()) {
        return OpTokenResult::NOT_FOUND;
    }
    OperationToken& ot = it->second;

    if (ot.username != expected_username) {
        return OpTokenResult::NOT_FOUND; // don't leak which part mismatched to a wrong-username caller
    }
    if (ot.used) {
        return OpTokenResult::USED;
    }
    time_t now = time(nullptr);
    if (now > ot.expires_at) {
        return OpTokenResult::EXPIRED;
    }
    if (ot.operation != expected_operation) {
        return OpTokenResult::WRONG_OPERATION;
    }
    if (ot.target_service != expected_target) {
        return OpTokenResult::WRONG_TARGET;
    }

    // All checks passed - consume it now, inside the same locked section.
    ot.used = true;
    return OpTokenResult::VALID;
}


#include <openssl/evp.h>  // Already included in your original code

// Argon2id password hashing (libsodium).
// crypto_pwhash_str() generates a random salt internally and returns a
// single self-describing string of the form:
//   $argon2id$v=19$m=<mem_kb>,t=<iterations>,p=<parallelism>$<salt>$<hash>
// That string is everything we need to store - no separate salt column.
string hashPassword(const string& password) {
    char hashed[crypto_pwhash_STRBYTES]; // 128 bytes, includes algo+params+salt+hash, null-terminated

    if (crypto_pwhash_str(
            hashed,
            password.c_str(),
            password.size(),
            crypto_pwhash_OPSLIMIT_INTERACTIVE,   // CPU cost (~2 iterations)
            crypto_pwhash_MEMLIMIT_INTERACTIVE    // memory cost (~64 MiB)
        ) != 0) {
        // Only fails on OOM, which on a login server usually means
        // something else is badly wrong - treat as a hard failure.
        cerr << "Error hashing password (out of memory)" << endl;
        return "";
    }

    return string(hashed);
}

// Verify a plaintext password against a stored Argon2id hash string.
// Salt and parameters are embedded in storedHash, so no extra arguments
// are needed - this replaces the old "re-hash and compare strings" approach,
// which doesn't work once each hash has its own random salt.
bool verifyPassword(const string& storedHash, const string& password) {
    return crypto_pwhash_str_verify(
        storedHash.c_str(),
        password.c_str(),
        password.size()
    ) == 0;
}


void loadUserDatabase() {
    ifstream file("users.txt");
    if (!file.is_open()) return;

    string line;
    while (getline(file, line)) {
        size_t space = line.find(' ');
        if (space != string::npos) {
            string username = line.substr(0, space);
            string passwordHash = line.substr(space + 1);
            // libsodium's Argon2id strings always start with this prefix.
            if (passwordHash.rfind("$argon2id$", 0) == 0) {
                userDatabase[username] = passwordHash;
            } else {
                cerr << "Invalid password hash format for user: " << username << endl;
            }
        }
    }
}

void saveUserDatabase(const string& username, const string& password) {
    lock_guard<mutex> lock(file_mutex);
    ofstream file("users.txt", ios::app);
    if (file.is_open()) {
        file << username << " " << password << "\n";
    }
}

bool authenticateUser(const string& username, const string& password) {
    if (!userDatabase.count(username)) return false;
    return verifyPassword(userDatabase[username], password);
}
bool registerUser(const string& username, const string& password) {
    if (userDatabase.count(username)) return false;
    string hashedPassword = hashPassword(password);
    if (hashedPassword.empty()) return false; // hashing failed (OOM) - don't store a broken account
    userDatabase[username] = hashedPassword;
    saveUserDatabase(username, hashedPassword);
    return true;
}

void storeEmail(const string& recipient, const string& email) {
    lock_guard<mutex> lock(file_mutex);
    ofstream outFile(recipient + "_emails.txt", ios::app | ios::binary);
    if (outFile.is_open()) {
        // Verify the email has 7 parts before storing
        size_t count = std::count(email.begin(), email.end(), '~');
        if (count != 6) { // 6 delimiters = 7 parts
            cerr << "ERROR: Invalid email format when storing (expected 7 parts)\n";
            return;
        }
        outFile << email << "\n---EMAIL_END---\n";
        outFile.flush();
    }
}

string retrieveEmails(const string& username) {
    lock_guard<mutex> lock(file_mutex);  // Thread safety

    // --- Phase 1: Read Emails ---
    string filename = username + "_emails.txt";
    ifstream inFile(filename, ios::binary);
    
    if (!inFile.is_open()) {
        cout << "[STATUS] No emails found for " << username << endl;
        return "No emails found\n---EMAIL_END---\n";
    }

    // Read content
    stringstream buffer;
    buffer << inFile.rdbuf();
    string content = buffer.str();
    inFile.close();

    // A drained mailbox file is truncated, not deleted (see Phase 2 below),
    // so on every poll after the first one this file exists but is empty -
    // that must be treated identically to "file never existed" rather than
    // falling through to the generic "---EMAIL_END---"-only response below
    // (which the client has no placeholder text for).
    if (content.find_first_not_of(" \n\r\t") == string::npos) {
        cout << "[STATUS] No emails found for " << username << endl;
        return "No emails found\n---EMAIL_END---\n";
    }

    // Ensure proper termination
    if (content.find("---EMAIL_END---") == string::npos) {
        content += "\n---EMAIL_END---\n";
    }

    // --- Phase 2: Clear File ---
    ofstream outFile(filename, ios::trunc | ios::binary);
    if (!outFile) {
        cerr << "[ERROR] Failed to clear email file for " << username << endl;
        // Still return the content we managed to read
        return content;
    }
    outFile.close();

    cout << "[STATUS] Emails retrieved and storage cleared for " << username << endl;
    return content;
}

// handleClient now operates on an already-handshaked TLS session (SSL*)
// instead of a raw socket fd. Every send()/recv()/read_line() call below
// is the TLS equivalent (tls_send/tls_recv/tls_read_line); the message
// formats, parsing, and control flow are unchanged from the plain-TCP
// version.
void handleClient(SSL* ssl) {
    loadUserDatabase();
    string username;
    char buffer[BUFFER_SIZE] = {0};
    bool authenticated = false;

    // Authentication
    while (!authenticated) {
        int bytes = tls_recv(ssl, buffer, BUFFER_SIZE);
        if (bytes <= 0) break;

        string received(buffer, bytes);
        vector<string> parts;
        size_t pos = 0;
        
        while ((pos = received.find('\n')) != string::npos) {
            string part = received.substr(0, pos);
            if (!part.empty()) parts.push_back(part);
            received.erase(0, pos + 1);
        }

        if (parts.size() >= 3) {
            string choice = parts[0];
            username = parts[1];
            string password = parts[2];
            
            if (choice == "1") { // Login
                if (authenticateUser(username, password)) {
                    string token = startSession(username);
                    string resp = "AUTH_SUCCESS\n" + token + "\n";
                    tls_send(ssl, resp.c_str(), resp.size());
                    authenticated = true;
                } else {
                    tls_send(ssl, "AUTH_FAILED\n", 12);
                }
            } else if (choice == "2") { // Signup
                if (registerUser(username, password)) {
                    string token = startSession(username);
                    string resp = "AUTH_SUCCESS\n" + token + "\n";
                    tls_send(ssl, resp.c_str(), resp.size());
                    authenticated = true;
                } else {
                    tls_send(ssl, "USER_EXISTS\n", 12);
                }
            }
        }
    }

    // Rest of your email handling code..

    // Email operations
  while (authenticated) {
        string command = tls_read_line(ssl);

        // tls_read_line() returns "" both for a literal empty line AND for a
        // closed/disconnected session (tls_recv() keeps returning 0 forever
        // once the peer's TLS shutdown / FIN has been received). No real
        // command in this protocol is ever empty, so treat it as a
        // disconnect signal and stop - otherwise this becomes an infinite
        // busy loop spinning at 100% CPU the moment a client closes its
        // connection without first sending "0".
        if (command.empty()) {
            cout << "[STATUS] Client disconnected without sending exit command." << endl;
            break;
        }

        cout << "Received command: " << command << endl;

        if (command == "REQUEST_OP_TOKEN") {
            // Wire format: "REQUEST_OP_TOKEN\n<operation>\n<target_service>\n"
            // Client must already be authenticated to reach this branch at
            // all (we're inside `while (authenticated)`), so no separate
            // session-token re-check is needed here - same trust basis the
            // existing EMAIL_SEND/"4" commands in this loop already rely on.
            string operation = tls_read_line(ssl);
            string target_service = tls_read_line(ssl);

            static const std::vector<string> kValidOps = {
                "STORE_SHARE1", "STORE_SHARE2", "FETCH_SHARE1",
                "GET_SHARE", "UPDATE_SHARE1", "UPDATE_SHARE2"
            };
            bool op_ok = std::find(kValidOps.begin(), kValidOps.end(), operation) != kValidOps.end();
            bool target_ok = (target_service == "KEYSERVER" || target_service == "RECOVERYSERVER");

            if (!op_ok || !target_ok) {
                cerr << "[OPTOKEN] Rejected REQUEST_OP_TOKEN: bad operation/target ("
                     << operation << " / " << target_service << ")" << endl;
                tls_send(ssl, "ERROR:INVALID_OPERATION_OR_TARGET\n", 35);
                continue;
            }

            string op_token = generateOperationToken(username, operation, target_service);
            if (op_token.empty()) {
                tls_send(ssl, "ERROR:OP_TOKEN_GENERATION_FAILED\n", 34);
                continue;
            }

            string resp = "OP_TOKEN\n" + op_token + "\n";
            tls_send(ssl, resp.c_str(), resp.size());
        }
        else if (command == "EMAIL_SEND") {
            // Read recipient
            string recipient = tls_read_line(ssl);
            if (recipient.empty()) {
                tls_send(ssl, "ERROR:NO_RECIPIENT\n", 19);
                continue;
            }

            // Read email packet
            string email_packet = tls_read_line(ssl);
            if (email_packet.empty()) {
                tls_send(ssl, "ERROR:NO_DATA\n", 14);
                continue;
            }

            // Verify end marker
            string end_marker = tls_read_line(ssl);
            if (end_marker != "END_TRANSMISSION") {
                tls_send(ssl, "ERROR:INVALID_END_MARKER\n", 24);
                continue;
            }

            // Store email
            storeEmail(recipient, email_packet);
            tls_send(ssl, "OK:EMAIL_STORED\n", 16);
            cout << "Stored email for " << recipient << endl;
        }
      else if (command == "4") { // Retrieve emails
    string emails = retrieveEmails(username);
    if (emails.empty()) {
        emails = "No emails found\n---EMAIL_END---\n";
    }
    
    // Convert BUFFER_SIZE to size_t for comparison
    size_t buffer_size = static_cast<size_t>(BUFFER_SIZE);
    size_t total_sent = 0;
    
    while (total_sent < emails.size()) {
        size_t chunk_size = std::min(buffer_size, emails.size() - total_sent);
        int bytes = tls_send(ssl,
                        emails.c_str() + total_sent, 
                        chunk_size);
        if (bytes <= 0) {
            cerr << "Failed to send email data\n";
            break;
        }
        total_sent += bytes;
    }
}
        else if (command == "0") { // Exit
            break;
        }
    }
    endSession(username);
    tls_close(ssl);
}

// --- Internal server-to-server verification listener ---
// KeyServer/RecoveryServer connect here (now over TLS) to confirm a
// (username, token) pair is a real, currently-active GmailServer session
// before trusting any key/share operation.
void handleVerifyConnection(SSL* ssl) {
    string line1 = tls_read_line(ssl); // expected: "VERIFY" or "VERIFY_OP"

    if (line1 == "VERIFY_OP") {
        // Wire format: "VERIFY_OP\n<username>\n<operation>\n<target_service>\n<op_token>\n"
        // Response: "VALID\n" | "USED\n" | "EXPIRED\n" | "WRONG_OPERATION\n" |
        //           "WRONG_TARGET\n" | "NOT_FOUND\n" | "MALFORMED\n"
        // This is purely additive: the original "VERIFY" branch below (and
        // everything isSessionValid/activeSessions does) is completely
        // unchanged - KeyServer/RecoveryServer still make that exact same
        // call, in addition to this new one, for every share operation.
        string username = tls_read_line(ssl);
        string operation = tls_read_line(ssl);
        string target_service = tls_read_line(ssl);
        string op_token = tls_read_line(ssl);

#if TOKEN_DEBUG
        cout << "[OPTOKEN] VERIFY_OP request received: user=" << username
             << " op=" << operation << " target=" << target_service << endl;
#endif

        if (username.empty() || operation.empty() || target_service.empty() || op_token.empty()) {
            tls_send(ssl, "MALFORMED\n", 10);
            tls_close(ssl);
            return;
        }

        OpTokenResult result = verifyAndConsumeOperationToken(username, operation, target_service, op_token);

#if TOKEN_DEBUG
        cout << "[OPTOKEN] VERIFY_OP result = " << opTokenResultStr(result) << endl;
#endif

        string resp = string(opTokenResultStr(result)) + "\n";
        tls_send(ssl, resp.c_str(), resp.size());
        tls_close(ssl);
        return;
    }

    // ---- Existing VERIFY (session token) path - unchanged ----
    string username = tls_read_line(ssl);
    string token = tls_read_line(ssl);

#if TOKEN_DEBUG
    cout << "[TOKEN] VERIFY request received" << endl;
#endif

    if (line1 != "VERIFY" || username.empty() || token.empty()) {
        tls_send(ssl, "INVALID\n", 8);
        tls_close(ssl);
        return;
    }

    if (isSessionValid(username, token)) {
        tls_send(ssl, "VALID\n", 6);
    } else {
        tls_send(ssl, "INVALID\n", 8);
    }
    tls_close(ssl);
}

void runVerifyServer(SSL_CTX* server_ctx) {
    int verifySocket = socket(AF_INET, SOCK_STREAM, 0);
    if (verifySocket < 0) {
        cerr << "Verify socket creation failed\n";
        return;
    }

    int opt = 1;
    setsockopt(verifySocket, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    sockaddr_in verifyAddr;
    verifyAddr.sin_family = AF_INET;
    verifyAddr.sin_addr.s_addr = INADDR_ANY; // see note: restrict at firewall/network level for localhost-only deployments
    verifyAddr.sin_port = htons(VERIFY_PORT);

    if (bind(verifySocket, (sockaddr*)&verifyAddr, sizeof(verifyAddr)) < 0) {
        cerr << "Verify port bind failed\n";
        return;
    }

    if (listen(verifySocket, 10) < 0) {
        cerr << "Verify port listen failed\n";
        return;
    }

    cout << "Internal session-verify listener (TLS) running on port " << VERIFY_PORT << endl;

    while (true) {
        sockaddr_in addr;
        socklen_t addrLen = sizeof(addr);
        int sock = accept(verifySocket, (sockaddr*)&addr, &addrLen);
        if (sock < 0) {
            cerr << "Verify accept failed\n";
            continue;
        }
        SSL* ssl = tls_server_accept(sock, server_ctx);
        if (!ssl) {
            cerr << "Verify TLS handshake failed; dropping connection\n";
            continue;
        }
        thread(handleVerifyConnection, ssl).detach();
    }
}

int main() {
    if (sodium_init() < 0) {
        cerr << "FATAL: libsodium initialization failed\n";
        return 1;
    }

    // ---- Signed Session Tokens (Phase 1) ----
    // Generate GmailServer's token-signing keypair if it doesn't exist yet.
    // Separate from, and independent of, the TLS identity loaded below.
    {
        ifstream priv_key(GMAIL_SIGNING_PRIVATE_KEY_PATH);
        ifstream pub_key(GMAIL_SIGNING_PUBLIC_KEY_PATH);
        if (!priv_key.good() || !pub_key.good()) {
            cout << "[TOKEN] Generating GmailServer signing keypair..." << endl;
            generateGmailSigningKeys();
        }
    }

    tls_global_init();
    SSL_CTX* server_ctx = tls_create_server_ctx(TLS_CERT_PATH, TLS_KEY_PATH);
    if (!server_ctx) {
        cerr << "FATAL: Could not load TLS certificate/key ("
             << TLS_CERT_PATH << " / " << TLS_KEY_PATH << "). "
             << "Run certs/gen_certs.sh first.\n";
        return 1;
    }

    int serverSocket = socket(AF_INET, SOCK_STREAM, 0);
    if (serverSocket < 0) {
        cerr << "Socket creation failed\n";
        return 1;
    }

    sockaddr_in serverAddr;
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_addr.s_addr = INADDR_ANY;
    serverAddr.sin_port = htons(PORT);

    if (bind(serverSocket, (sockaddr*)&serverAddr, sizeof(serverAddr)) < 0) {
        cerr << "Bind failed\n";
        return 1;
    }

    if (listen(serverSocket, 10) < 0) {
        cerr << "Listen failed\n";
        return 1;
    }

    cout << "Gmail Server running on port " << PORT << " (TLS)" << endl;

    // Start the internal verify listener in its own thread (also TLS,
    // using the same server certificate).
    thread(runVerifyServer, server_ctx).detach();

    while (true) {
        sockaddr_in clientAddr;
        socklen_t addrLen = sizeof(clientAddr);
        int clientSocket = accept(serverSocket, (sockaddr*)&clientAddr, &addrLen);
        if (clientSocket < 0) {
            cerr << "Accept failed\n";
            continue;
        }
        SSL* ssl = tls_server_accept(clientSocket, server_ctx);
        if (!ssl) {
            cerr << "Client TLS handshake failed; dropping connection\n";
            continue;
        }
        thread(handleClient, ssl).detach();
    }

    close(serverSocket);
    return 0;
}