// tls_common.h
//
// Small shared TLS transport layer used by client.cpp, gmailserver.cpp,
// keyserver.cpp, and recovery_server.cpp.
//
// Scope: this module ONLY replaces the plain-TCP send()/recv()/connect()/
// accept()/close() calls those files used to make with TLS-wrapped
// equivalents that have the same blocking, byte-stream semantics. It does
// not know anything about the application's message formats (LOGIN|...,
// STORE_SHARE|..., VERIFY|..., etc.) - those are unchanged in every
// caller; only the transport under them changed.
//
// Trust model (deliberately simple, matching "self-signed, no external
// CA" requirement):
//   - Each server (GmailServer, KeyServer, RecoveryServer) has its own
//     self-signed certificate + private key, generated by
//     certs/gen_certs.sh, and presents that certificate to anyone who
//     connects to it (tls_create_server_ctx + tls_server_accept).
//   - Every TLS *client* role in this project (the end-user client.cpp,
//     and KeyServer/RecoveryServer when they call out to GmailServer's
//     internal verify port) trusts exactly the bundle of those
//     self-signed certs (certs/trusted_servers.pem) - no system/OS CA
//     store is consulted (tls_create_client_ctx).
//   - Because every endpoint here is 127.0.0.1 (or, if you later split
//     the servers across machines, a small fixed set of known hosts) and
//     the certs are pinned by file rather than issued by a CA, we
//     intentionally do NOT perform hostname/SAN verification - only
//     "is this certificate (or its issuer) one of the ones we pinned"
//     verification (SSL_CTX_load_verify_locations + SSL_VERIFY_PEER).
//     If you later deploy across real, separate hosts, add
//     SSL_set1_host()/X509_VERIFY_PARAM hostname checks in
//     tls_client_connect() using the cert's CN/SAN.
//
// Every function here mirrors the plain-socket call it replaces:
//   connect()                  -> tls_client_connect()
//   accept()+nothing           -> tls_server_accept()  (raw accept() is
//                                 still called by the caller; this just
//                                 layers TLS on top of the already-
//                                 accepted fd)
//   recv()/read()              -> tls_recv()
//   send()/write()             -> tls_send()
//   the project's read_line()  -> tls_read_line()
//   setsockopt(SO_RCVTIMEO)    -> tls_set_recv_timeout()
//   close()                    -> tls_close()

#ifndef TLS_COMMON_H
#define TLS_COMMON_H

#include <openssl/ssl.h>
#include <string>
#include <cstddef>

// Call once, before any other tls_* function (each server/client main()
// does this exactly once at startup). Initializes OpenSSL's TLS error
// strings and algorithms. Safe to call more than once.
void tls_global_init();

// ---- Server-side context/handshake ----

// Builds an SSL_CTX for a server identity: loads cert_path as this
// server's certificate chain and key_path as its private key, and
// verifies the two match. Returns nullptr (after printing the OpenSSL
// error queue to stderr) if either file is missing/unreadable or the
// key doesn't match the cert - callers must check for nullptr and
// treat it as a fatal startup error (same "can't start without this"
// severity as a failed bind()/listen()).
SSL_CTX* tls_create_server_ctx(const char* cert_path, const char* key_path);

// Wraps an already-accept()-ed raw socket fd in a TLS server session and
// performs the handshake. On handshake failure, cleans up internally and
// returns nullptr - the caller's existing "drop this connection and keep
// looping" pattern (just like a failed accept()) requires no further
// cleanup of the fd from the caller in that case.
SSL* tls_server_accept(int raw_fd, SSL_CTX* server_ctx);

// ---- Client-side context/connect ----

// Builds an SSL_CTX for a TLS client role: trusts exactly the
// certificate(s) found in trusted_bundle_path (a PEM file - typically
// the concatenation of all the project's server certs, see
// certs/gen_certs.sh) and nothing else. Returns nullptr if the bundle
// file is missing/unreadable/empty.
SSL_CTX* tls_create_client_ctx(const char* trusted_bundle_path);

// Opens a TCP connection to ip:port and performs a TLS handshake as a
// client, verifying the peer's certificate against client_ctx's trust
// store. Returns nullptr on any failure (DNS/connect failure, handshake
// failure, or certificate verification failure) - same "give up, this
// attempt failed" semantics the old connect_to_server() had when it
// returned -1.
SSL* tls_client_connect(const char* ip, int port, SSL_CTX* client_ctx);

// ---- I/O (mirrors send()/recv() return semantics: >0 bytes transferred,
//      0 on orderly shutdown, <0 on error) ----

int tls_send(SSL* ssl, const char* data, size_t len);
int tls_recv(SSL* ssl, char* buf, size_t len);

// Reads a single '\n'-terminated line, byte by byte, identical in
// behavior to the project's original plain-socket read_line(): the
// trailing '\n' is consumed but not included in the returned string,
// and a closed/erroring connection (recv()<=0 at any point, including
// immediately) yields "" - the same "" the original returned both for a
// literal empty line and for disconnection, which every caller already
// handles.
std::string tls_read_line(SSL* ssl);

// Sets a receive timeout (SO_RCVTIMEO) on the socket underlying ssl, in
// whole seconds. Mirrors the struct timeval / setsockopt(SO_RCVTIMEO)
// pattern the project used for the GmailServer-verify-port calls.
void tls_set_recv_timeout(SSL* ssl, int seconds);

// Shuts down the TLS session, frees it, and closes the underlying
// socket fd. Safe to call with ssl == nullptr (no-op). Mirrors close().
void tls_close(SSL* ssl);

#endif // TLS_COMMON_H
